title: À écouter
email: florent+podcast@dufour.xyz
description: >-
  Une collection à écouter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://podcast.dufour.xyz" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
lang: fr-FR
owner: Florent Dufour

plugins:
  - jekyll-liquify
#  - jekyll-feed

exclude:
  - README.md
  - Makefile
  - .gitignore
  - favicon.ico
  - Gemfile*
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
