title: Podcasts
email: florent+podcast@dufour.xyz
description: >-
  Une collection à écouter.
url: "https://podcast.dufour.xyz"
encoding: utf-8
lang: fr-FR
owner: Florent Dufour

collections:
  nav:
    output: true

exclude:
  - README.md
  - Makefile
  - .gitignore
  - favicon.ico
  - Gemfile*
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/